[env:esp8266]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0

build_flags =
    -Wno-unused-variable
    -Wno-unused-parameter

; Opcje optymalizacji - odkomentuj dla wiekszej wydajnosci
; board_build.f_cpu = 160000000L
; board_build.flash_mode = qio
; board_build.f_flash = 40000000L
